<?php
########################################################################
#
# Auto generated by Fluid-Template-Manager
#
# www.fluid-template-manager.de
#
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'FTM - Theme',
    'description' => 'Theme to use Twitter Bootstrap',
    'category' => 'templates',
    'shy' => 0,
    'version' => '1.0.0',
    'dependencies' => '',
    'conflicts' => '',
    'priority' => '',
    'loadOrder' => '',
    'module' => '',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'modify_tables' => '',
    'clearcacheonload' => 0,
    'lockType' => '',
    'author' => 'Themes-Team',
    'author_email' => 'team@typo3-themes.org',
    'author_company' => '',
    'CGLcompliance' => '',
    'CGLcompliance_note' => '',
    'constraints' => array(
        'depends' => array(
            'typo3'  => '6.2.0-6.2.99',
            'themes' => '1.0.1-1.0.1',
            'belayout_fileprovider' => '0.0.1-0.0.1',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
    '_md5_values_when_last_written' => 'a:0:{}',
);